name: flutter_application_1
description: "A new Flutter project."

# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"
# consider running `flutter pub upgrade --major-versions`. 
# versions available, run `flutter pub outdated`.
dependencies:
  # `flutter pub add provider`
  provider: ^6.1.2

  flutter:
    sdk: flutter
  liquid_swipe: ^3.1.0

  image_picker: ^1.1.2
  curved_navigation_bar: ^1.0.6
  fluttertoast: ^8.2.6
  intl: ^0.19.0
  http: ^1.2.1

  cloud_firestore: ^5.0.2
  flutter_carousel_slider: ^1.1.0
  firebase_core: ^3.1.1
  # firebase_auth: ^5.1.1

  # 47. Onboarding_Screen_with_dot_indicator.dart
  introduction_screen: ^3.1.14

  # 48. Shared_Preferences
  shared_preferences: ^2.2.3

  # 52
  google_mobile_ads: ^5.1.0

  # 53
  url_launcher: ^6.3.0

  # 55
  webview_flutter: ^4.9.0

  # flutter_launcher_icons: ^0.13.1

  # android: "launcher_icon"
  # ios: true
  # image_path: "images/launcher_icons.png"
  # min_sdk_android: 21

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #58
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 49. Change_Flutter_App_Icon_And_App_Name.dart
  flutter_launcher_icons: ^0.14.1
flutter_icons:
  android: true
  ios: true
  image_path: "images/launcher_icons.png"

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/ss.png
    - images/ss1.png
    - images/ss2.png
    - images/ss3.png

